
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Movie.Net
{

using System;
    using System.Collections.Generic;
    
public partial class Comments
{

    public int Id { get; set; }

    public string Rating { get; set; }

    public string Comment { get; set; }

    public int MoviesId { get; set; }

    public int UserId { get; set; }



    public virtual Movies Movie { get; set; }

    public virtual User User { get; set; }

}

}
