//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movie.Net
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int Id { get; set; }
        public string Rating { get; set; }
        public string Comment { get; set; }
        public int MoviesId { get; set; }
        public int UserId { get; set; }
    
        public virtual Movies Movie { get; set; }
        public virtual User User { get; set; }
    }
}
